-- Seed: 50 items for age band 3-5 (Phase 1 pilot)
-- 13 items each for reasoning, math, pattern_recognition; 11 for verbal
-- Difficulty spread from -2.0 to 2.0; discrimination 0.8–2.0; guessing 0.15–0.25

-- ─── Reasoning Items (13) ───────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('reasoning', 'analogies', '{3-5}', -1.5, 1.0, 0.25, '{"stem": "Apple is to tree as egg is to ___", "type": "analogy", "options": [{"text": "Nest"}, {"text": "Plate"}, {"text": "Chicken"}, {"text": "Egg carton"}], "correct_index": 2, "media": ["apple.svg", "tree.svg", "egg.svg"]}'),
('reasoning', 'analogies', '{3-5}', -1.0, 1.2, 0.25, '{"stem": "Glove is to hand as sock is to ___", "type": "analogy", "options": [{"text": "Shoe"}, {"text": "Foot"}, {"text": "Leg"}, {"text": "Drawer"}], "correct_index": 1}'),
('reasoning', 'analogies', '{3-5}', -0.5, 1.1, 0.25, '{"stem": "Puppy is to dog as kitten is to ___", "type": "analogy", "options": [{"text": "Mouse"}, {"text": "Cat"}, {"text": "Bird"}, {"text": "Rabbit"}], "correct_index": 1}'),
('reasoning', 'classification', '{3-5}', 0.0, 1.3, 0.25, '{"stem": "Which one does NOT belong?", "type": "odd_one_out", "options": [{"text": "Carrot"}, {"text": "Banana"}, {"text": "Broccoli"}, {"text": "Spinach"}], "correct_index": 1}'),
('reasoning', 'classification', '{3-5}', 0.5, 1.4, 0.20, '{"stem": "Which one does NOT belong?", "type": "odd_one_out", "options": [{"text": "Triangle"}, {"text": "Square"}, {"text": "Circle"}, {"text": "Cube"}], "correct_index": 3}'),
('reasoning', 'series', '{3-5}', 0.0, 1.2, 0.25, '{"stem": "What comes next? 2, 4, 6, 8, ___", "type": "number_series", "options": [{"text": "9"}, {"text": "10"}, {"text": "12"}, {"text": "11"}], "correct_index": 1}'),
('reasoning', 'series', '{3-5}', 0.5, 1.3, 0.20, '{"stem": "What comes next? 1, 3, 5, 7, ___", "type": "number_series", "options": [{"text": "8"}, {"text": "9"}, {"text": "10"}, {"text": "11"}], "correct_index": 1}'),
('reasoning', 'series', '{3-5}', 1.0, 1.5, 0.20, '{"stem": "What comes next? 2, 6, 18, 54, ___", "type": "number_series", "options": [{"text": "108"}, {"text": "162"}, {"text": "72"}, {"text": "216"}], "correct_index": 1}'),
('reasoning', 'logical', '{3-5}', 1.0, 1.6, 0.20, '{"stem": "All Bloops are Zips. Some Zips are Wops. Can some Bloops be Wops?", "type": "syllogism", "options": [{"text": "Yes, always"}, {"text": "Yes, sometimes"}, {"text": "No, never"}, {"text": "Not enough info"}], "correct_index": 1}'),
('reasoning', 'logical', '{3-5}', 1.5, 1.7, 0.15, '{"stem": "If it is raining, the ground is wet. The ground is wet. Is it raining?", "type": "syllogism", "options": [{"text": "Yes, definitely"}, {"text": "Maybe"}, {"text": "No"}, {"text": "Not enough info"}], "correct_index": 1}'),
('reasoning', 'analogies', '{3-5}', -2.0, 0.8, 0.25, '{"stem": "Hot is to cold as up is to ___", "type": "analogy", "options": [{"text": "Down"}, {"text": "Left"}, {"text": "Over"}, {"text": "Under"}], "correct_index": 0}'),
('reasoning', 'analogies', '{3-5}', 1.5, 1.8, 0.15, '{"stem": "Book is to library as painting is to ___", "type": "analogy", "options": [{"text": "Canvas"}, {"text": "Museum"}, {"text": "Artist"}, {"text": "Frame"}], "correct_index": 1}'),
('reasoning', 'classification', '{3-5}', 2.0, 2.0, 0.15, '{"stem": "Which one does NOT belong? Mercury, Venus, Moon, Mars", "type": "odd_one_out", "options": [{"text": "Mercury"}, {"text": "Venus"}, {"text": "Moon"}, {"text": "Mars"}], "correct_index": 2}');

-- ─── Math Items (13) ────────────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('math', 'number_sense', '{3-5}', -2.0, 0.9, 0.25, '{"stem": "Which number is bigger?", "type": "comparison", "options": [{"text": "15"}, {"text": "51"}], "correct_index": 1}'),
('math', 'number_sense', '{3-5}', -1.5, 1.0, 0.25, '{"stem": "What is 7 + 8?", "type": "computation", "options": [{"text": "13"}, {"text": "14"}, {"text": "15"}, {"text": "16"}], "correct_index": 2}'),
('math', 'computation', '{3-5}', -1.0, 1.1, 0.25, '{"stem": "What is 23 + 19?", "type": "computation", "options": [{"text": "41"}, {"text": "42"}, {"text": "43"}, {"text": "32"}], "correct_index": 1}'),
('math', 'computation', '{3-5}', -0.5, 1.2, 0.25, '{"stem": "What is 6 × 7?", "type": "computation", "options": [{"text": "36"}, {"text": "42"}, {"text": "48"}, {"text": "35"}], "correct_index": 1}'),
('math', 'problem_solving', '{3-5}', 0.0, 1.3, 0.25, '{"stem": "A baker made 48 cookies. She puts them in bags of 6. How many bags?", "type": "word_problem", "options": [{"text": "6"}, {"text": "7"}, {"text": "8"}, {"text": "9"}], "correct_index": 2}'),
('math', 'problem_solving', '{3-5}', 0.5, 1.4, 0.20, '{"stem": "48 cookies in bags of 6. If she gives 2 bags per friend, how many friends get cookies?", "type": "word_problem", "options": [{"text": "3"}, {"text": "4"}, {"text": "6"}, {"text": "8"}], "correct_index": 1}'),
('math', 'fractions', '{3-5}', 0.5, 1.3, 0.25, '{"stem": "Which is bigger: 1/3 or 1/4?", "type": "comparison", "options": [{"text": "1/3"}, {"text": "1/4"}, {"text": "They are equal"}], "correct_index": 0}'),
('math', 'fractions', '{3-5}', 1.0, 1.5, 0.20, '{"stem": "What is 1/2 + 1/4?", "type": "computation", "options": [{"text": "2/6"}, {"text": "3/4"}, {"text": "1/2"}, {"text": "2/4"}], "correct_index": 1}'),
('math', 'problem_solving', '{3-5}', 1.0, 1.4, 0.20, '{"stem": "A train travels 60 miles per hour. How far does it go in 2.5 hours?", "type": "word_problem", "options": [{"text": "120 miles"}, {"text": "130 miles"}, {"text": "150 miles"}, {"text": "180 miles"}], "correct_index": 2}'),
('math', 'number_sense', '{3-5}', 1.5, 1.6, 0.15, '{"stem": "What is the next prime number after 13?", "type": "number_sense", "options": [{"text": "14"}, {"text": "15"}, {"text": "17"}, {"text": "19"}], "correct_index": 2}'),
('math', 'computation', '{3-5}', 1.5, 1.7, 0.15, '{"stem": "What is 144 ÷ 12?", "type": "computation", "options": [{"text": "11"}, {"text": "12"}, {"text": "13"}, {"text": "14"}], "correct_index": 1}'),
('math', 'problem_solving', '{3-5}', 2.0, 2.0, 0.15, '{"stem": "A rectangle has perimeter 24cm and width 4cm. What is its area?", "type": "word_problem", "options": [{"text": "32 sq cm"}, {"text": "20 sq cm"}, {"text": "48 sq cm"}, {"text": "24 sq cm"}], "correct_index": 0}'),
('math', 'computation', '{3-5}', -1.5, 1.0, 0.25, '{"stem": "What is 50 - 23?", "type": "computation", "options": [{"text": "23"}, {"text": "27"}, {"text": "33"}, {"text": "37"}], "correct_index": 1}');

-- ─── Verbal Items (11) ──────────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('verbal', 'vocabulary', '{3-5}', -1.5, 1.0, 0.25, '{"stem": "What does \"enormous\" mean?", "type": "definition", "options": [{"text": "Very small"}, {"text": "Very fast"}, {"text": "Very big"}, {"text": "Very old"}], "correct_index": 2}'),
('verbal', 'vocabulary', '{3-5}', -1.0, 1.1, 0.25, '{"stem": "What is a synonym for \"happy\"?", "type": "synonym", "options": [{"text": "Sad"}, {"text": "Joyful"}, {"text": "Angry"}, {"text": "Tired"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{3-5}', -0.5, 1.2, 0.25, '{"stem": "What is the opposite of \"ancient\"?", "type": "antonym", "options": [{"text": "Old"}, {"text": "Modern"}, {"text": "Classic"}, {"text": "Historic"}], "correct_index": 1}'),
('verbal', 'reading_comprehension', '{3-5}', 0.0, 1.3, 0.25, '{"stem": "Sam ran to the store because he needed milk. Why did Sam go to the store?", "type": "comprehension", "options": [{"text": "To buy bread"}, {"text": "To get milk"}, {"text": "To see a friend"}, {"text": "To exercise"}], "correct_index": 1}'),
('verbal', 'inference', '{3-5}', 0.5, 1.4, 0.20, '{"stem": "Maria put on her raincoat and grabbed her umbrella. What can you infer about the weather?", "type": "inference", "options": [{"text": "It is sunny"}, {"text": "It is raining or about to rain"}, {"text": "It is snowing"}, {"text": "It is windy"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{3-5}', 0.5, 1.3, 0.20, '{"stem": "What does \"reluctant\" mean?", "type": "definition", "options": [{"text": "Eager"}, {"text": "Unwilling"}, {"text": "Confused"}, {"text": "Excited"}], "correct_index": 1}'),
('verbal', 'inference', '{3-5}', 1.0, 1.5, 0.20, '{"stem": "The dog wagged its tail and brought its leash to the door. What does the dog want?", "type": "inference", "options": [{"text": "Food"}, {"text": "A walk"}, {"text": "Sleep"}, {"text": "A bath"}], "correct_index": 1}'),
('verbal', 'reading_comprehension', '{3-5}', 1.0, 1.5, 0.20, '{"stem": "The library was quiet. Everyone whispered. Books lined every wall. Where is this?", "type": "comprehension", "options": [{"text": "A school gym"}, {"text": "A library"}, {"text": "A park"}, {"text": "A store"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{3-5}', 1.5, 1.7, 0.15, '{"stem": "What does \"ubiquitous\" mean?", "type": "definition", "options": [{"text": "Very rare"}, {"text": "Found everywhere"}, {"text": "Very beautiful"}, {"text": "Hard to understand"}], "correct_index": 1}'),
('verbal', 'inference', '{3-5}', 1.5, 1.6, 0.15, '{"stem": "After the earthquake, the family slept outside in a tent. Why?", "type": "inference", "options": [{"text": "They like camping"}, {"text": "Their house may be unsafe"}, {"text": "It was summer"}, {"text": "The tent was new"}], "correct_index": 1}'),
('verbal', 'reading_comprehension', '{3-5}', 2.0, 1.8, 0.15, '{"stem": "The scientist carefully recorded each measurement twice. What does this tell you about the scientist?", "type": "comprehension", "options": [{"text": "She is bored"}, {"text": "She is thorough and careful"}, {"text": "She is slow"}, {"text": "She forgot the first time"}], "correct_index": 1}');

-- ─── Pattern Recognition Items (13) ─────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('pattern_recognition', 'sequences', '{3-5}', -2.0, 0.8, 0.25, '{"stem": "What color comes next? Red, Blue, Red, Blue, ___", "type": "color_pattern", "options": [{"text": "Red"}, {"text": "Blue"}, {"text": "Green"}, {"text": "Yellow"}], "correct_index": 0}'),
('pattern_recognition', 'sequences', '{3-5}', -1.5, 1.0, 0.25, '{"stem": "What shape comes next? Circle, Square, Circle, Square, ___", "type": "shape_pattern", "options": [{"text": "Triangle"}, {"text": "Circle"}, {"text": "Square"}, {"text": "Star"}], "correct_index": 1}'),
('pattern_recognition', 'sequences', '{3-5}', -1.0, 1.1, 0.25, '{"stem": "What comes next? AB, CD, EF, ___", "type": "letter_pattern", "options": [{"text": "FG"}, {"text": "GH"}, {"text": "HI"}, {"text": "EF"}], "correct_index": 1}'),
('pattern_recognition', 'matrices', '{3-5}', -0.5, 1.2, 0.25, '{"stem": "Complete the pattern in the grid", "type": "matrix", "options": [{"text": "Option A", "image": "matrix_1a.svg"}, {"text": "Option B", "image": "matrix_1b.svg"}, {"text": "Option C", "image": "matrix_1c.svg"}, {"text": "Option D", "image": "matrix_1d.svg"}], "correct_index": 2, "media": ["matrix_1_grid.svg"]}'),
('pattern_recognition', 'spatial', '{3-5}', 0.0, 1.3, 0.25, '{"stem": "If you fold this shape, what will it look like?", "type": "spatial_fold", "options": [{"text": "Option A", "image": "fold_1a.svg"}, {"text": "Option B", "image": "fold_1b.svg"}, {"text": "Option C", "image": "fold_1c.svg"}, {"text": "Option D", "image": "fold_1d.svg"}], "correct_index": 0, "media": ["fold_1_flat.svg"]}'),
('pattern_recognition', 'sequences', '{3-5}', 0.0, 1.2, 0.25, '{"stem": "What comes next? 1, 1, 2, 3, 5, ___", "type": "number_pattern", "options": [{"text": "6"}, {"text": "7"}, {"text": "8"}, {"text": "10"}], "correct_index": 2}'),
('pattern_recognition', 'matrices', '{3-5}', 0.5, 1.4, 0.20, '{"stem": "Which piece completes the 3x3 grid?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 1, "media": ["matrix_2_grid.svg"]}'),
('pattern_recognition', 'spatial', '{3-5}', 0.5, 1.3, 0.20, '{"stem": "Which shape is the mirror image?", "type": "reflection", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 2, "media": ["mirror_1.svg"]}'),
('pattern_recognition', 'sequences', '{3-5}', 1.0, 1.5, 0.20, '{"stem": "What comes next? 3, 6, 12, 24, ___", "type": "number_pattern", "options": [{"text": "30"}, {"text": "36"}, {"text": "48"}, {"text": "32"}], "correct_index": 2}'),
('pattern_recognition', 'matrices', '{3-5}', 1.0, 1.5, 0.20, '{"stem": "Find the pattern: each row and column follow a rule. What goes in the empty cell?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 0, "media": ["matrix_3_grid.svg"]}'),
('pattern_recognition', 'spatial', '{3-5}', 1.5, 1.7, 0.15, '{"stem": "Which 3D shape can be made from this flat pattern (net)?", "type": "nets", "options": [{"text": "Cube"}, {"text": "Cylinder"}, {"text": "Pyramid"}, {"text": "Cone"}], "correct_index": 2, "media": ["net_1.svg"]}'),
('pattern_recognition', 'sequences', '{3-5}', 1.5, 1.6, 0.15, '{"stem": "What comes next? 2, 3, 5, 7, 11, ___", "type": "number_pattern", "options": [{"text": "12"}, {"text": "13"}, {"text": "14"}, {"text": "15"}], "correct_index": 1}'),
('pattern_recognition', 'matrices', '{3-5}', 2.0, 2.0, 0.15, '{"stem": "Complex 3x3 matrix with shape rotation and color change rules. Which completes it?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 3, "media": ["matrix_4_grid.svg"]}');
