-- Seed: 52 items for age band 6-8 (middle school, grades 6-8)
-- Harder content, higher difficulty range [-0.5, 3.0]
-- 13 items each for reasoning, math, pattern_recognition; 13 for verbal

-- ─── Reasoning Items (13) ───────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('reasoning', 'analogies', '{6-8}', -0.5, 1.2, 0.25, '{"stem": "Democracy is to government as capitalism is to ___", "type": "analogy", "options": [{"text": "Politics"}, {"text": "Economics"}, {"text": "Society"}, {"text": "Law"}], "correct_index": 1}'),
('reasoning', 'analogies', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "Microscope is to biology as telescope is to ___", "type": "analogy", "options": [{"text": "Physics"}, {"text": "Chemistry"}, {"text": "Astronomy"}, {"text": "Geology"}], "correct_index": 2}'),
('reasoning', 'analogies', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "Symphony is to composer as novel is to ___", "type": "analogy", "options": [{"text": "Reader"}, {"text": "Publisher"}, {"text": "Author"}, {"text": "Editor"}], "correct_index": 2}'),
('reasoning', 'classification', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "Which does NOT belong? Photosynthesis, Respiration, Evaporation, Fermentation", "type": "odd_one_out", "options": [{"text": "Photosynthesis"}, {"text": "Respiration"}, {"text": "Evaporation"}, {"text": "Fermentation"}], "correct_index": 2}'),
('reasoning', 'classification', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "Which does NOT belong? Simile, Metaphor, Hypothesis, Personification", "type": "odd_one_out", "options": [{"text": "Simile"}, {"text": "Metaphor"}, {"text": "Hypothesis"}, {"text": "Personification"}], "correct_index": 2}'),
('reasoning', 'series', '{6-8}', 0.5, 1.3, 0.20, '{"stem": "What comes next? 1, 4, 9, 16, 25, ___", "type": "number_series", "options": [{"text": "30"}, {"text": "36"}, {"text": "49"}, {"text": "32"}], "correct_index": 1}'),
('reasoning', 'series', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "What comes next? 1, 1, 2, 3, 5, 8, 13, ___", "type": "number_series", "options": [{"text": "18"}, {"text": "20"}, {"text": "21"}, {"text": "26"}], "correct_index": 2}'),
('reasoning', 'series', '{6-8}', 1.5, 1.7, 0.15, '{"stem": "What comes next? 2, 6, 12, 20, 30, ___", "type": "number_series", "options": [{"text": "40"}, {"text": "42"}, {"text": "36"}, {"text": "48"}], "correct_index": 1}'),
('reasoning', 'logical', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "All integers divisible by 6 are divisible by 3. 24 is divisible by 6. Which must be true?", "type": "syllogism", "options": [{"text": "24 is divisible by 3"}, {"text": "24 is divisible by 9"}, {"text": "All numbers divisible by 3 are divisible by 6"}, {"text": "24 is prime"}], "correct_index": 0}'),
('reasoning', 'logical', '{6-8}', 1.5, 1.7, 0.15, '{"stem": "If A implies B, and B implies C, what can we conclude?", "type": "syllogism", "options": [{"text": "C implies A"}, {"text": "A implies C"}, {"text": "Not A implies not C"}, {"text": "B implies A"}], "correct_index": 1}'),
('reasoning', 'logical', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "Some artists are musicians. All musicians practice daily. Which MUST be true?", "type": "syllogism", "options": [{"text": "All artists practice daily"}, {"text": "Some artists practice daily"}, {"text": "All who practice daily are musicians"}, {"text": "No artists practice daily"}], "correct_index": 1}'),
('reasoning', 'analogies', '{6-8}', 2.5, 2.0, 0.15, '{"stem": "Entropy is to thermodynamics as natural selection is to ___", "type": "analogy", "options": [{"text": "Genetics"}, {"text": "Evolution"}, {"text": "Ecology"}, {"text": "Taxonomy"}], "correct_index": 1}'),
('reasoning', 'classification', '{6-8}', 3.0, 2.0, 0.15, '{"stem": "Which does NOT belong? Correlation, Regression, Standard deviation, Allegory", "type": "odd_one_out", "options": [{"text": "Correlation"}, {"text": "Regression"}, {"text": "Standard deviation"}, {"text": "Allegory"}], "correct_index": 3}');

-- ─── Math Items (13) ────────────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('math', 'number_sense', '{6-8}', -0.5, 1.2, 0.25, '{"stem": "What is 15% of 200?", "type": "computation", "options": [{"text": "20"}, {"text": "25"}, {"text": "30"}, {"text": "35"}], "correct_index": 2}'),
('math', 'computation', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "Simplify: 3(x + 4) - 2x", "type": "algebra", "options": [{"text": "x + 12"}, {"text": "x + 4"}, {"text": "5x + 4"}, {"text": "5x + 12"}], "correct_index": 0}'),
('math', 'computation', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "Solve for x: 2x + 7 = 15", "type": "algebra", "options": [{"text": "3"}, {"text": "4"}, {"text": "5"}, {"text": "11"}], "correct_index": 1}'),
('math', 'fractions', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "What is 2/3 × 3/4?", "type": "computation", "options": [{"text": "6/12"}, {"text": "1/2"}, {"text": "5/7"}, {"text": "6/7"}], "correct_index": 1}'),
('math', 'fractions', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "Convert 0.375 to a fraction in simplest form", "type": "conversion", "options": [{"text": "3/8"}, {"text": "3/4"}, {"text": "375/100"}, {"text": "37/100"}], "correct_index": 0}'),
('math', 'problem_solving', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "A shirt costs $40. It is 25% off. Then you have a 10% coupon on the sale price. What do you pay?", "type": "word_problem", "options": [{"text": "$26.00"}, {"text": "$27.00"}, {"text": "$28.00"}, {"text": "$30.00"}], "correct_index": 1}'),
('math', 'problem_solving', '{6-8}', 1.5, 1.6, 0.15, '{"stem": "A pool fills at 3 gallons/min and drains at 1 gallon/min. If empty, how long to fill 120 gallons?", "type": "word_problem", "options": [{"text": "40 min"}, {"text": "60 min"}, {"text": "80 min"}, {"text": "120 min"}], "correct_index": 1}'),
('math', 'computation', '{6-8}', 1.5, 1.7, 0.15, '{"stem": "What is the value of 2^8?", "type": "computation", "options": [{"text": "128"}, {"text": "256"}, {"text": "512"}, {"text": "64"}], "correct_index": 1}'),
('math', 'problem_solving', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "A triangle has sides 5, 12, and 13. What is its area?", "type": "geometry", "options": [{"text": "30"}, {"text": "60"}, {"text": "65"}, {"text": "26"}], "correct_index": 0}'),
('math', 'number_sense', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "What is the greatest common factor (GCF) of 48 and 36?", "type": "number_theory", "options": [{"text": "6"}, {"text": "8"}, {"text": "12"}, {"text": "18"}], "correct_index": 2}'),
('math', 'computation', '{6-8}', 2.5, 2.0, 0.15, '{"stem": "Simplify: (x² - 9) / (x + 3)", "type": "algebra", "options": [{"text": "x - 3"}, {"text": "x + 3"}, {"text": "x² - 3"}, {"text": "x - 9"}], "correct_index": 0}'),
('math', 'problem_solving', '{6-8}', 2.5, 1.9, 0.15, '{"stem": "The probability of rain on any given day is 0.3. What is the probability of NO rain for 3 consecutive days?", "type": "probability", "options": [{"text": "0.343"}, {"text": "0.027"}, {"text": "0.7"}, {"text": "0.9"}], "correct_index": 0}'),
('math', 'computation', '{6-8}', 3.0, 2.0, 0.15, '{"stem": "If f(x) = 3x² - 2x + 1, what is f(−1)?", "type": "function_eval", "options": [{"text": "2"}, {"text": "4"}, {"text": "6"}, {"text": "0"}], "correct_index": 2}');

-- ─── Verbal Items (13) ──────────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('verbal', 'vocabulary', '{6-8}', -0.5, 1.2, 0.25, '{"stem": "What does \"ambiguous\" mean?", "type": "definition", "options": [{"text": "Very clear"}, {"text": "Open to more than one interpretation"}, {"text": "Extremely ambitious"}, {"text": "Lacking energy"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "What is an antonym of \"benevolent\"?", "type": "antonym", "options": [{"text": "Generous"}, {"text": "Malevolent"}, {"text": "Indifferent"}, {"text": "Brilliant"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "The word \"ephemeral\" means:", "type": "definition", "options": [{"text": "Lasting a very short time"}, {"text": "Extremely important"}, {"text": "Related to astronomy"}, {"text": "Very beautiful"}], "correct_index": 0}'),
('verbal', 'reading_comprehension', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "The author describes the character''s clenched fists and tight jaw. This suggests the character feels:", "type": "comprehension", "options": [{"text": "Relaxed"}, {"text": "Angry or tense"}, {"text": "Confused"}, {"text": "Excited"}], "correct_index": 1}'),
('verbal', 'inference', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "A news article reports that a company laid off 30% of workers, then its stock price rose. What can be inferred?", "type": "inference", "options": [{"text": "Workers were unproductive"}, {"text": "Investors valued cost reduction"}, {"text": "The company is failing"}, {"text": "Stock prices always rise after layoffs"}], "correct_index": 1}'),
('verbal', 'reading_comprehension', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "The author uses the phrase ''a double-edged sword'' to describe technology. This means technology:", "type": "figurative_language", "options": [{"text": "Is dangerous"}, {"text": "Has both benefits and drawbacks"}, {"text": "Is medieval"}, {"text": "Should be avoided"}], "correct_index": 1}'),
('verbal', 'inference', '{6-8}', 1.5, 1.6, 0.15, '{"stem": "A historian writes: ''The treaty, while celebrated at the time, planted the seeds of future conflict.'' The historian believes:", "type": "inference", "options": [{"text": "The treaty was entirely successful"}, {"text": "The treaty eventually led to problems"}, {"text": "Treaties never work"}, {"text": "The celebration was premature but the treaty worked"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{6-8}', 1.5, 1.7, 0.15, '{"stem": "What does \"pragmatic\" mean?", "type": "definition", "options": [{"text": "Idealistic"}, {"text": "Dealing with things practically"}, {"text": "Dramatic"}, {"text": "Ancient"}], "correct_index": 1}'),
('verbal', 'reading_comprehension', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "An author writes about poverty using statistics AND a personal story. Why use both approaches?", "type": "rhetoric", "options": [{"text": "To make the writing longer"}, {"text": "Statistics prove the point; the story makes it emotionally real"}, {"text": "One approach was not enough pages"}, {"text": "The personal story replaces the statistics"}], "correct_index": 1}'),
('verbal', 'inference', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "Two scientists publish opposing conclusions from the same data. What is the BEST explanation?", "type": "critical_thinking", "options": [{"text": "One scientist is wrong"}, {"text": "The data is flawed"}, {"text": "They used different analytical frameworks or assumptions"}, {"text": "Science cannot answer this question"}], "correct_index": 2}'),
('verbal', 'vocabulary', '{6-8}', 2.5, 2.0, 0.15, '{"stem": "''Juxtaposition'' in literature refers to:", "type": "definition", "options": [{"text": "Placing contrasting elements side by side"}, {"text": "Writing from multiple perspectives"}, {"text": "Using legal language in fiction"}, {"text": "Breaking the fourth wall"}], "correct_index": 0}'),
('verbal', 'reading_comprehension', '{6-8}', 2.5, 1.9, 0.15, '{"stem": "A satirist writes ''The committee, in its infinite wisdom, decided to solve homelessness by painting the park benches an unpleasant color.'' The tone is:", "type": "tone_analysis", "options": [{"text": "Sincere and praising"}, {"text": "Sarcastic and critical"}, {"text": "Neutral and informative"}, {"text": "Sympathetic and sad"}], "correct_index": 1}'),
('verbal', 'inference', '{6-8}', 3.0, 2.0, 0.15, '{"stem": "An author argues that standardized tests measure socioeconomic status more than intelligence. What would MOST weaken this argument?", "type": "critical_thinking", "options": [{"text": "Many wealthy students score poorly"}, {"text": "Test scores correlate with family income"}, {"text": "Students from all backgrounds score similarly when given equal test prep"}, {"text": "Test prep companies exist"}], "correct_index": 0}');

-- ─── Pattern Recognition Items (13) ─────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('pattern_recognition', 'sequences', '{6-8}', -0.5, 1.2, 0.25, '{"stem": "What comes next? 3, 7, 11, 15, ___", "type": "number_pattern", "options": [{"text": "17"}, {"text": "18"}, {"text": "19"}, {"text": "20"}], "correct_index": 2}'),
('pattern_recognition', 'sequences', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "What comes next? 2, 3, 5, 7, 11, 13, ___", "type": "number_pattern", "options": [{"text": "15"}, {"text": "17"}, {"text": "19"}, {"text": "14"}], "correct_index": 1}'),
('pattern_recognition', 'sequences', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "What comes next? 1, 8, 27, 64, ___", "type": "number_pattern", "options": [{"text": "100"}, {"text": "125"}, {"text": "81"}, {"text": "216"}], "correct_index": 1}'),
('pattern_recognition', 'matrices', '{6-8}', 0.5, 1.3, 0.20, '{"stem": "In this 3x3 grid, shapes rotate 90° across columns and change color across rows. What goes in the empty cell?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 2, "media": ["matrix_68_1.svg"]}'),
('pattern_recognition', 'spatial', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "Which 3D shape results from rotating this 2D cross-section 360° around the axis?", "type": "rotation_3d", "options": [{"text": "Sphere"}, {"text": "Cylinder"}, {"text": "Cone"}, {"text": "Torus"}], "correct_index": 2, "media": ["rotate3d_1.svg"]}'),
('pattern_recognition', 'matrices', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "Two rules govern this grid: size increases left-to-right, shading alternates top-to-bottom. What completes it?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 0, "media": ["matrix_68_2.svg"]}'),
('pattern_recognition', 'sequences', '{6-8}', 1.5, 1.6, 0.15, '{"stem": "What comes next? 1, 3, 7, 15, 31, ___", "type": "number_pattern", "options": [{"text": "47"}, {"text": "55"}, {"text": "62"}, {"text": "63"}], "correct_index": 3}'),
('pattern_recognition', 'spatial', '{6-8}', 1.5, 1.7, 0.15, '{"stem": "This net folds into a cube. Which two faces are opposite each other?", "type": "nets", "options": [{"text": "A and C"}, {"text": "A and F"}, {"text": "B and E"}, {"text": "C and D"}], "correct_index": 1, "media": ["cube_net_1.svg"]}'),
('pattern_recognition', 'matrices', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "This 4x4 grid uses three simultaneous rules (shape, size, shading). What completes the bottom-right cell?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 1, "media": ["matrix_68_3.svg"]}'),
('pattern_recognition', 'spatial', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "A paper is folded twice and a hole is punched. When unfolded, how many holes appear?", "type": "paper_fold", "options": [{"text": "2"}, {"text": "3"}, {"text": "4"}, {"text": "8"}], "correct_index": 2, "media": ["fold_68_1.svg"]}'),
('pattern_recognition', 'sequences', '{6-8}', 2.5, 2.0, 0.15, '{"stem": "What comes next? 1, 11, 21, 1211, 111221, ___", "type": "number_pattern", "options": [{"text": "312211"}, {"text": "122211"}, {"text": "1112221"}, {"text": "221121"}], "correct_index": 0}'),
('pattern_recognition', 'matrices', '{6-8}', 2.5, 1.9, 0.15, '{"stem": "This grid applies XOR logic to shapes: combining two shapes produces a third. What completes the pattern?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 3, "media": ["matrix_68_4.svg"]}'),
('pattern_recognition', 'spatial', '{6-8}', 3.0, 2.0, 0.15, '{"stem": "A cube has different patterns on each face. After the shown sequence of rotations, which face is on top?", "type": "mental_rotation", "options": [{"text": "Stripes"}, {"text": "Dots"}, {"text": "Solid"}, {"text": "Checkerboard"}], "correct_index": 1, "media": ["cube_rotate_1.svg"]}');
