-- Seed: 52 items for age band K-2 (younger learners, grades K-2)
-- Simpler content, lower difficulty range [-2.5, 1.0]
-- 13 items each for reasoning, math, pattern_recognition; 13 for verbal

-- ─── Reasoning Items (13) ───────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('reasoning', 'analogies', '{K-2}', -2.5, 0.8, 0.25, '{"stem": "A bird can fly. A fish can ___", "type": "analogy", "options": [{"text": "Swim"}, {"text": "Run"}, {"text": "Fly"}, {"text": "Jump"}], "correct_index": 0}'),
('reasoning', 'analogies', '{K-2}', -2.0, 0.9, 0.25, '{"stem": "A hat goes on your head. A shoe goes on your ___", "type": "analogy", "options": [{"text": "Hand"}, {"text": "Foot"}, {"text": "Head"}, {"text": "Arm"}], "correct_index": 1}'),
('reasoning', 'analogies', '{K-2}', -1.5, 1.0, 0.25, '{"stem": "Night is dark. Day is ___", "type": "analogy", "options": [{"text": "Dark"}, {"text": "Cold"}, {"text": "Light"}, {"text": "Warm"}], "correct_index": 2}'),
('reasoning', 'classification', '{K-2}', -2.0, 0.8, 0.25, '{"stem": "Which one is NOT an animal?", "type": "odd_one_out", "options": [{"text": "Dog"}, {"text": "Cat"}, {"text": "Chair"}, {"text": "Bird"}], "correct_index": 2}'),
('reasoning', 'classification', '{K-2}', -1.5, 0.9, 0.25, '{"stem": "Which one is NOT a fruit?", "type": "odd_one_out", "options": [{"text": "Apple"}, {"text": "Banana"}, {"text": "Carrot"}, {"text": "Grape"}], "correct_index": 2}'),
('reasoning', 'classification', '{K-2}', -1.0, 1.0, 0.25, '{"stem": "Which one does NOT have wheels?", "type": "odd_one_out", "options": [{"text": "Car"}, {"text": "Bicycle"}, {"text": "Boat"}, {"text": "Truck"}], "correct_index": 2}'),
('reasoning', 'series', '{K-2}', -2.0, 0.8, 0.25, '{"stem": "What comes next? 1, 2, 3, 4, ___", "type": "number_series", "options": [{"text": "4"}, {"text": "5"}, {"text": "6"}, {"text": "7"}], "correct_index": 1}'),
('reasoning', 'series', '{K-2}', -1.5, 0.9, 0.25, '{"stem": "What comes next? A, B, C, D, ___", "type": "letter_series", "options": [{"text": "F"}, {"text": "E"}, {"text": "D"}, {"text": "G"}], "correct_index": 1}'),
('reasoning', 'series', '{K-2}', -0.5, 1.1, 0.25, '{"stem": "What comes next? 2, 4, 6, ___", "type": "number_series", "options": [{"text": "7"}, {"text": "8"}, {"text": "9"}, {"text": "10"}], "correct_index": 1}'),
('reasoning', 'logical', '{K-2}', -0.5, 1.0, 0.25, '{"stem": "All dogs have tails. Buddy is a dog. Does Buddy have a tail?", "type": "syllogism", "options": [{"text": "Yes"}, {"text": "No"}, {"text": "Maybe"}, {"text": "We don''t know"}], "correct_index": 0}'),
('reasoning', 'logical', '{K-2}', 0.0, 1.2, 0.25, '{"stem": "If you are wet, you were in the rain. Tom is wet. Was Tom in the rain?", "type": "syllogism", "options": [{"text": "Yes, for sure"}, {"text": "Maybe"}, {"text": "No"}, {"text": "We can''t tell"}], "correct_index": 1}'),
('reasoning', 'analogies', '{K-2}', 0.5, 1.3, 0.20, '{"stem": "Pen is to write as scissors is to ___", "type": "analogy", "options": [{"text": "Draw"}, {"text": "Cut"}, {"text": "Glue"}, {"text": "Tape"}], "correct_index": 1}'),
('reasoning', 'classification', '{K-2}', 1.0, 1.4, 0.20, '{"stem": "Which one does NOT belong? Ice cream, popsicle, snowflake, soup", "type": "odd_one_out", "options": [{"text": "Ice cream"}, {"text": "Popsicle"}, {"text": "Snowflake"}, {"text": "Soup"}], "correct_index": 3}');

-- ─── Math Items (13) ────────────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('math', 'number_sense', '{K-2}', -2.5, 0.8, 0.25, '{"stem": "How many apples are there? 🍎🍎🍎", "type": "counting", "options": [{"text": "2"}, {"text": "3"}, {"text": "4"}, {"text": "5"}], "correct_index": 1}'),
('math', 'number_sense', '{K-2}', -2.0, 0.8, 0.25, '{"stem": "Which number is bigger: 3 or 7?", "type": "comparison", "options": [{"text": "3"}, {"text": "7"}], "correct_index": 1}'),
('math', 'number_sense', '{K-2}', -2.0, 0.9, 0.25, '{"stem": "What number comes after 9?", "type": "number_sense", "options": [{"text": "8"}, {"text": "10"}, {"text": "11"}, {"text": "20"}], "correct_index": 1}'),
('math', 'computation', '{K-2}', -1.5, 0.9, 0.25, '{"stem": "What is 3 + 2?", "type": "computation", "options": [{"text": "4"}, {"text": "5"}, {"text": "6"}, {"text": "7"}], "correct_index": 1}'),
('math', 'computation', '{K-2}', -1.5, 1.0, 0.25, '{"stem": "What is 8 - 3?", "type": "computation", "options": [{"text": "4"}, {"text": "5"}, {"text": "6"}, {"text": "3"}], "correct_index": 1}'),
('math', 'computation', '{K-2}', -1.0, 1.0, 0.25, '{"stem": "What is 6 + 7?", "type": "computation", "options": [{"text": "12"}, {"text": "13"}, {"text": "14"}, {"text": "11"}], "correct_index": 1}'),
('math', 'computation', '{K-2}', -0.5, 1.1, 0.25, '{"stem": "What is 15 - 8?", "type": "computation", "options": [{"text": "6"}, {"text": "7"}, {"text": "8"}, {"text": "9"}], "correct_index": 1}'),
('math', 'problem_solving', '{K-2}', -1.0, 1.0, 0.25, '{"stem": "You have 4 cookies and get 3 more. How many cookies do you have?", "type": "word_problem", "options": [{"text": "5"}, {"text": "6"}, {"text": "7"}, {"text": "8"}], "correct_index": 2}'),
('math', 'problem_solving', '{K-2}', -0.5, 1.1, 0.25, '{"stem": "There are 10 birds on a fence. 4 fly away. How many are left?", "type": "word_problem", "options": [{"text": "4"}, {"text": "5"}, {"text": "6"}, {"text": "7"}], "correct_index": 2}'),
('math', 'problem_solving', '{K-2}', 0.0, 1.2, 0.25, '{"stem": "Emma has 3 bags with 4 stickers in each bag. How many stickers total?", "type": "word_problem", "options": [{"text": "7"}, {"text": "10"}, {"text": "12"}, {"text": "14"}], "correct_index": 2}'),
('math', 'number_sense', '{K-2}', 0.0, 1.1, 0.25, '{"stem": "What is half of 10?", "type": "number_sense", "options": [{"text": "3"}, {"text": "4"}, {"text": "5"}, {"text": "6"}], "correct_index": 2}'),
('math', 'computation', '{K-2}', 0.5, 1.2, 0.20, '{"stem": "What is 2 + 2 + 2 + 2?", "type": "computation", "options": [{"text": "6"}, {"text": "8"}, {"text": "10"}, {"text": "4"}], "correct_index": 1}'),
('math', 'problem_solving', '{K-2}', 1.0, 1.3, 0.20, '{"stem": "A toy costs 25 cents. You have 3 dimes. Do you have enough money?", "type": "word_problem", "options": [{"text": "Yes, with 5 cents left"}, {"text": "Yes, exact change"}, {"text": "No, need 5 more cents"}, {"text": "No, need 10 more cents"}], "correct_index": 0}');

-- ─── Verbal Items (13) ──────────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('verbal', 'vocabulary', '{K-2}', -2.5, 0.8, 0.25, '{"stem": "What is the baby of a cat called?", "type": "definition", "options": [{"text": "Puppy"}, {"text": "Kitten"}, {"text": "Cub"}, {"text": "Chick"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{K-2}', -2.0, 0.8, 0.25, '{"stem": "What color do you get when you mix red and white?", "type": "knowledge", "options": [{"text": "Orange"}, {"text": "Purple"}, {"text": "Pink"}, {"text": "Brown"}], "correct_index": 2}'),
('verbal', 'vocabulary', '{K-2}', -1.5, 0.9, 0.25, '{"stem": "Which word means the same as \"little\"?", "type": "synonym", "options": [{"text": "Big"}, {"text": "Small"}, {"text": "Tall"}, {"text": "Fast"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{K-2}', -1.0, 1.0, 0.25, '{"stem": "What is the opposite of \"hot\"?", "type": "antonym", "options": [{"text": "Warm"}, {"text": "Cold"}, {"text": "Wet"}, {"text": "Dry"}], "correct_index": 1}'),
('verbal', 'reading_comprehension', '{K-2}', -1.5, 0.9, 0.25, '{"stem": "The cat sat on the mat. Where is the cat?", "type": "comprehension", "options": [{"text": "On the bed"}, {"text": "On the mat"}, {"text": "Under the table"}, {"text": "On the chair"}], "correct_index": 1}'),
('verbal', 'reading_comprehension', '{K-2}', -0.5, 1.1, 0.25, '{"stem": "Tom was sad because his balloon flew away. How did Tom feel?", "type": "comprehension", "options": [{"text": "Happy"}, {"text": "Sad"}, {"text": "Angry"}, {"text": "Scared"}], "correct_index": 1}'),
('verbal', 'inference', '{K-2}', -0.5, 1.0, 0.25, '{"stem": "The dog is barking at the door. What might the dog want?", "type": "inference", "options": [{"text": "To sleep"}, {"text": "To eat"}, {"text": "To go outside"}, {"text": "To play with a ball"}], "correct_index": 2}'),
('verbal', 'inference', '{K-2}', 0.0, 1.2, 0.25, '{"stem": "Lucy put on her boots and grabbed her umbrella. What is the weather probably like?", "type": "inference", "options": [{"text": "Sunny"}, {"text": "Rainy"}, {"text": "Snowy"}, {"text": "Windy"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{K-2}', 0.0, 1.1, 0.25, '{"stem": "What does \"tiny\" mean?", "type": "definition", "options": [{"text": "Very big"}, {"text": "Very small"}, {"text": "Very loud"}, {"text": "Very fast"}], "correct_index": 1}'),
('verbal', 'reading_comprehension', '{K-2}', 0.5, 1.2, 0.20, '{"stem": "The boy ate pizza, then ice cream, then cookies. What did he eat first?", "type": "comprehension", "options": [{"text": "Ice cream"}, {"text": "Cookies"}, {"text": "Pizza"}, {"text": "Cake"}], "correct_index": 2}'),
('verbal', 'inference', '{K-2}', 0.5, 1.3, 0.20, '{"stem": "The flowers in the garden are drooping and the soil is dry. What do the flowers need?", "type": "inference", "options": [{"text": "Sunshine"}, {"text": "Water"}, {"text": "Music"}, {"text": "Wind"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{K-2}', 1.0, 1.4, 0.20, '{"stem": "What does \"curious\" mean?", "type": "definition", "options": [{"text": "Scared"}, {"text": "Wanting to learn or know"}, {"text": "Very tired"}, {"text": "Feeling sick"}], "correct_index": 1}'),
('verbal', 'reading_comprehension', '{K-2}', 1.0, 1.3, 0.20, '{"stem": "First, Maya brushed her teeth. Then she put on pajamas. Last, she read a book. What is Maya getting ready for?", "type": "comprehension", "options": [{"text": "School"}, {"text": "A party"}, {"text": "Bed"}, {"text": "Dinner"}], "correct_index": 2}');

-- ─── Pattern Recognition Items (13) ─────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('pattern_recognition', 'sequences', '{K-2}', -2.5, 0.8, 0.25, '{"stem": "What color comes next? Red, Red, Blue, Red, Red, ___", "type": "color_pattern", "options": [{"text": "Red"}, {"text": "Blue"}, {"text": "Green"}, {"text": "Yellow"}], "correct_index": 1}'),
('pattern_recognition', 'sequences', '{K-2}', -2.0, 0.8, 0.25, '{"stem": "What comes next? Big, Small, Big, Small, ___", "type": "size_pattern", "options": [{"text": "Small"}, {"text": "Big"}, {"text": "Medium"}, {"text": "Tiny"}], "correct_index": 1}'),
('pattern_recognition', 'sequences', '{K-2}', -2.0, 0.9, 0.25, '{"stem": "What shape comes next? ⭐ 🔵 ⭐ 🔵 ___", "type": "shape_pattern", "options": [{"text": "🔵"}, {"text": "⭐"}, {"text": "🔺"}, {"text": "🟩"}], "correct_index": 1}'),
('pattern_recognition', 'sequences', '{K-2}', -1.5, 0.9, 0.25, '{"stem": "What comes next? 1, 2, 1, 2, 1, ___", "type": "number_pattern", "options": [{"text": "1"}, {"text": "2"}, {"text": "3"}, {"text": "4"}], "correct_index": 1}'),
('pattern_recognition', 'spatial', '{K-2}', -1.5, 0.9, 0.25, '{"stem": "Which shape is the same as the one shown but turned around?", "type": "rotation", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 1, "media": ["rotate_k2_1.svg"]}'),
('pattern_recognition', 'sequences', '{K-2}', -1.0, 1.0, 0.25, '{"stem": "What comes next? 🍎 🍊 🍎 🍊 🍎 ___", "type": "object_pattern", "options": [{"text": "🍎"}, {"text": "🍊"}, {"text": "🍋"}, {"text": "🍇"}], "correct_index": 1}'),
('pattern_recognition', 'matrices', '{K-2}', -1.0, 1.0, 0.25, '{"stem": "Look at the grid. Which picture goes in the empty box?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 0, "media": ["matrix_k2_1.svg"]}'),
('pattern_recognition', 'sequences', '{K-2}', -0.5, 1.1, 0.25, '{"stem": "What comes next? 🔴 🔵 🟢 🔴 🔵 ___", "type": "color_pattern", "options": [{"text": "🔴"}, {"text": "🔵"}, {"text": "🟢"}, {"text": "🟡"}], "correct_index": 2}'),
('pattern_recognition', 'spatial', '{K-2}', -0.5, 1.0, 0.25, '{"stem": "Which picture shows the shape flipped like a mirror?", "type": "reflection", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 2, "media": ["mirror_k2_1.svg"]}'),
('pattern_recognition', 'sequences', '{K-2}', 0.0, 1.2, 0.25, '{"stem": "What comes next? 1, 2, 3, 1, 2, 3, 1, 2, ___", "type": "number_pattern", "options": [{"text": "1"}, {"text": "2"}, {"text": "3"}, {"text": "4"}], "correct_index": 2}'),
('pattern_recognition', 'matrices', '{K-2}', 0.0, 1.1, 0.25, '{"stem": "Each row follows a rule. Which picture completes the last row?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 1, "media": ["matrix_k2_2.svg"]}'),
('pattern_recognition', 'spatial', '{K-2}', 0.5, 1.2, 0.20, '{"stem": "If you cut this folded paper and unfold it, what will it look like?", "type": "paper_fold", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 0, "media": ["fold_k2_1.svg"]}'),
('pattern_recognition', 'sequences', '{K-2}', 1.0, 1.4, 0.20, '{"stem": "What comes next? 2, 4, 6, 8, ___", "type": "number_pattern", "options": [{"text": "9"}, {"text": "10"}, {"text": "11"}, {"text": "12"}], "correct_index": 1}');
-- Seed: 52 items for age band 6-8 (middle school, grades 6-8)
-- Harder content, higher difficulty range [-0.5, 3.0]
-- 13 items each for reasoning, math, pattern_recognition; 13 for verbal

-- ─── Reasoning Items (13) ───────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('reasoning', 'analogies', '{6-8}', -0.5, 1.2, 0.25, '{"stem": "Democracy is to government as capitalism is to ___", "type": "analogy", "options": [{"text": "Politics"}, {"text": "Economics"}, {"text": "Society"}, {"text": "Law"}], "correct_index": 1}'),
('reasoning', 'analogies', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "Microscope is to biology as telescope is to ___", "type": "analogy", "options": [{"text": "Physics"}, {"text": "Chemistry"}, {"text": "Astronomy"}, {"text": "Geology"}], "correct_index": 2}'),
('reasoning', 'analogies', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "Symphony is to composer as novel is to ___", "type": "analogy", "options": [{"text": "Reader"}, {"text": "Publisher"}, {"text": "Author"}, {"text": "Editor"}], "correct_index": 2}'),
('reasoning', 'classification', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "Which does NOT belong? Photosynthesis, Respiration, Evaporation, Fermentation", "type": "odd_one_out", "options": [{"text": "Photosynthesis"}, {"text": "Respiration"}, {"text": "Evaporation"}, {"text": "Fermentation"}], "correct_index": 2}'),
('reasoning', 'classification', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "Which does NOT belong? Simile, Metaphor, Hypothesis, Personification", "type": "odd_one_out", "options": [{"text": "Simile"}, {"text": "Metaphor"}, {"text": "Hypothesis"}, {"text": "Personification"}], "correct_index": 2}'),
('reasoning', 'series', '{6-8}', 0.5, 1.3, 0.20, '{"stem": "What comes next? 1, 4, 9, 16, 25, ___", "type": "number_series", "options": [{"text": "30"}, {"text": "36"}, {"text": "49"}, {"text": "32"}], "correct_index": 1}'),
('reasoning', 'series', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "What comes next? 1, 1, 2, 3, 5, 8, 13, ___", "type": "number_series", "options": [{"text": "18"}, {"text": "20"}, {"text": "21"}, {"text": "26"}], "correct_index": 2}'),
('reasoning', 'series', '{6-8}', 1.5, 1.7, 0.15, '{"stem": "What comes next? 2, 6, 12, 20, 30, ___", "type": "number_series", "options": [{"text": "40"}, {"text": "42"}, {"text": "36"}, {"text": "48"}], "correct_index": 1}'),
('reasoning', 'logical', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "All integers divisible by 6 are divisible by 3. 24 is divisible by 6. Which must be true?", "type": "syllogism", "options": [{"text": "24 is divisible by 3"}, {"text": "24 is divisible by 9"}, {"text": "All numbers divisible by 3 are divisible by 6"}, {"text": "24 is prime"}], "correct_index": 0}'),
('reasoning', 'logical', '{6-8}', 1.5, 1.7, 0.15, '{"stem": "If A implies B, and B implies C, what can we conclude?", "type": "syllogism", "options": [{"text": "C implies A"}, {"text": "A implies C"}, {"text": "Not A implies not C"}, {"text": "B implies A"}], "correct_index": 1}'),
('reasoning', 'logical', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "Some artists are musicians. All musicians practice daily. Which MUST be true?", "type": "syllogism", "options": [{"text": "All artists practice daily"}, {"text": "Some artists practice daily"}, {"text": "All who practice daily are musicians"}, {"text": "No artists practice daily"}], "correct_index": 1}'),
('reasoning', 'analogies', '{6-8}', 2.5, 2.0, 0.15, '{"stem": "Entropy is to thermodynamics as natural selection is to ___", "type": "analogy", "options": [{"text": "Genetics"}, {"text": "Evolution"}, {"text": "Ecology"}, {"text": "Taxonomy"}], "correct_index": 1}'),
('reasoning', 'classification', '{6-8}', 3.0, 2.0, 0.15, '{"stem": "Which does NOT belong? Correlation, Regression, Standard deviation, Allegory", "type": "odd_one_out", "options": [{"text": "Correlation"}, {"text": "Regression"}, {"text": "Standard deviation"}, {"text": "Allegory"}], "correct_index": 3}');

-- ─── Math Items (13) ────────────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('math', 'number_sense', '{6-8}', -0.5, 1.2, 0.25, '{"stem": "What is 15% of 200?", "type": "computation", "options": [{"text": "20"}, {"text": "25"}, {"text": "30"}, {"text": "35"}], "correct_index": 2}'),
('math', 'computation', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "Simplify: 3(x + 4) - 2x", "type": "algebra", "options": [{"text": "x + 12"}, {"text": "x + 4"}, {"text": "5x + 4"}, {"text": "5x + 12"}], "correct_index": 0}'),
('math', 'computation', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "Solve for x: 2x + 7 = 15", "type": "algebra", "options": [{"text": "3"}, {"text": "4"}, {"text": "5"}, {"text": "11"}], "correct_index": 1}'),
('math', 'fractions', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "What is 2/3 × 3/4?", "type": "computation", "options": [{"text": "6/12"}, {"text": "1/2"}, {"text": "5/7"}, {"text": "6/7"}], "correct_index": 1}'),
('math', 'fractions', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "Convert 0.375 to a fraction in simplest form", "type": "conversion", "options": [{"text": "3/8"}, {"text": "3/4"}, {"text": "375/100"}, {"text": "37/100"}], "correct_index": 0}'),
('math', 'problem_solving', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "A shirt costs $40. It is 25% off. Then you have a 10% coupon on the sale price. What do you pay?", "type": "word_problem", "options": [{"text": "$26.00"}, {"text": "$27.00"}, {"text": "$28.00"}, {"text": "$30.00"}], "correct_index": 1}'),
('math', 'problem_solving', '{6-8}', 1.5, 1.6, 0.15, '{"stem": "A pool fills at 3 gallons/min and drains at 1 gallon/min. If empty, how long to fill 120 gallons?", "type": "word_problem", "options": [{"text": "40 min"}, {"text": "60 min"}, {"text": "80 min"}, {"text": "120 min"}], "correct_index": 1}'),
('math', 'computation', '{6-8}', 1.5, 1.7, 0.15, '{"stem": "What is the value of 2^8?", "type": "computation", "options": [{"text": "128"}, {"text": "256"}, {"text": "512"}, {"text": "64"}], "correct_index": 1}'),
('math', 'problem_solving', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "A triangle has sides 5, 12, and 13. What is its area?", "type": "geometry", "options": [{"text": "30"}, {"text": "60"}, {"text": "65"}, {"text": "26"}], "correct_index": 0}'),
('math', 'number_sense', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "What is the greatest common factor (GCF) of 48 and 36?", "type": "number_theory", "options": [{"text": "6"}, {"text": "8"}, {"text": "12"}, {"text": "18"}], "correct_index": 2}'),
('math', 'computation', '{6-8}', 2.5, 2.0, 0.15, '{"stem": "Simplify: (x² - 9) / (x + 3)", "type": "algebra", "options": [{"text": "x - 3"}, {"text": "x + 3"}, {"text": "x² - 3"}, {"text": "x - 9"}], "correct_index": 0}'),
('math', 'problem_solving', '{6-8}', 2.5, 1.9, 0.15, '{"stem": "The probability of rain on any given day is 0.3. What is the probability of NO rain for 3 consecutive days?", "type": "probability", "options": [{"text": "0.343"}, {"text": "0.027"}, {"text": "0.7"}, {"text": "0.9"}], "correct_index": 0}'),
('math', 'computation', '{6-8}', 3.0, 2.0, 0.15, '{"stem": "If f(x) = 3x² - 2x + 1, what is f(−1)?", "type": "function_eval", "options": [{"text": "2"}, {"text": "4"}, {"text": "6"}, {"text": "0"}], "correct_index": 2}');

-- ─── Verbal Items (13) ──────────────────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('verbal', 'vocabulary', '{6-8}', -0.5, 1.2, 0.25, '{"stem": "What does \"ambiguous\" mean?", "type": "definition", "options": [{"text": "Very clear"}, {"text": "Open to more than one interpretation"}, {"text": "Extremely ambitious"}, {"text": "Lacking energy"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "What is an antonym of \"benevolent\"?", "type": "antonym", "options": [{"text": "Generous"}, {"text": "Malevolent"}, {"text": "Indifferent"}, {"text": "Brilliant"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "The word \"ephemeral\" means:", "type": "definition", "options": [{"text": "Lasting a very short time"}, {"text": "Extremely important"}, {"text": "Related to astronomy"}, {"text": "Very beautiful"}], "correct_index": 0}'),
('verbal', 'reading_comprehension', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "The author describes the character''s clenched fists and tight jaw. This suggests the character feels:", "type": "comprehension", "options": [{"text": "Relaxed"}, {"text": "Angry or tense"}, {"text": "Confused"}, {"text": "Excited"}], "correct_index": 1}'),
('verbal', 'inference', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "A news article reports that a company laid off 30% of workers, then its stock price rose. What can be inferred?", "type": "inference", "options": [{"text": "Workers were unproductive"}, {"text": "Investors valued cost reduction"}, {"text": "The company is failing"}, {"text": "Stock prices always rise after layoffs"}], "correct_index": 1}'),
('verbal', 'reading_comprehension', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "The author uses the phrase ''a double-edged sword'' to describe technology. This means technology:", "type": "figurative_language", "options": [{"text": "Is dangerous"}, {"text": "Has both benefits and drawbacks"}, {"text": "Is medieval"}, {"text": "Should be avoided"}], "correct_index": 1}'),
('verbal', 'inference', '{6-8}', 1.5, 1.6, 0.15, '{"stem": "A historian writes: ''The treaty, while celebrated at the time, planted the seeds of future conflict.'' The historian believes:", "type": "inference", "options": [{"text": "The treaty was entirely successful"}, {"text": "The treaty eventually led to problems"}, {"text": "Treaties never work"}, {"text": "The celebration was premature but the treaty worked"}], "correct_index": 1}'),
('verbal', 'vocabulary', '{6-8}', 1.5, 1.7, 0.15, '{"stem": "What does \"pragmatic\" mean?", "type": "definition", "options": [{"text": "Idealistic"}, {"text": "Dealing with things practically"}, {"text": "Dramatic"}, {"text": "Ancient"}], "correct_index": 1}'),
('verbal', 'reading_comprehension', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "An author writes about poverty using statistics AND a personal story. Why use both approaches?", "type": "rhetoric", "options": [{"text": "To make the writing longer"}, {"text": "Statistics prove the point; the story makes it emotionally real"}, {"text": "One approach was not enough pages"}, {"text": "The personal story replaces the statistics"}], "correct_index": 1}'),
('verbal', 'inference', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "Two scientists publish opposing conclusions from the same data. What is the BEST explanation?", "type": "critical_thinking", "options": [{"text": "One scientist is wrong"}, {"text": "The data is flawed"}, {"text": "They used different analytical frameworks or assumptions"}, {"text": "Science cannot answer this question"}], "correct_index": 2}'),
('verbal', 'vocabulary', '{6-8}', 2.5, 2.0, 0.15, '{"stem": "''Juxtaposition'' in literature refers to:", "type": "definition", "options": [{"text": "Placing contrasting elements side by side"}, {"text": "Writing from multiple perspectives"}, {"text": "Using legal language in fiction"}, {"text": "Breaking the fourth wall"}], "correct_index": 0}'),
('verbal', 'reading_comprehension', '{6-8}', 2.5, 1.9, 0.15, '{"stem": "A satirist writes ''The committee, in its infinite wisdom, decided to solve homelessness by painting the park benches an unpleasant color.'' The tone is:", "type": "tone_analysis", "options": [{"text": "Sincere and praising"}, {"text": "Sarcastic and critical"}, {"text": "Neutral and informative"}, {"text": "Sympathetic and sad"}], "correct_index": 1}'),
('verbal', 'inference', '{6-8}', 3.0, 2.0, 0.15, '{"stem": "An author argues that standardized tests measure socioeconomic status more than intelligence. What would MOST weaken this argument?", "type": "critical_thinking", "options": [{"text": "Many wealthy students score poorly"}, {"text": "Test scores correlate with family income"}, {"text": "Students from all backgrounds score similarly when given equal test prep"}, {"text": "Test prep companies exist"}], "correct_index": 0}');

-- ─── Pattern Recognition Items (13) ─────────────────────────────

INSERT INTO items (domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json) VALUES
('pattern_recognition', 'sequences', '{6-8}', -0.5, 1.2, 0.25, '{"stem": "What comes next? 3, 7, 11, 15, ___", "type": "number_pattern", "options": [{"text": "17"}, {"text": "18"}, {"text": "19"}, {"text": "20"}], "correct_index": 2}'),
('pattern_recognition', 'sequences', '{6-8}', 0.0, 1.3, 0.25, '{"stem": "What comes next? 2, 3, 5, 7, 11, 13, ___", "type": "number_pattern", "options": [{"text": "15"}, {"text": "17"}, {"text": "19"}, {"text": "14"}], "correct_index": 1}'),
('pattern_recognition', 'sequences', '{6-8}', 0.5, 1.4, 0.20, '{"stem": "What comes next? 1, 8, 27, 64, ___", "type": "number_pattern", "options": [{"text": "100"}, {"text": "125"}, {"text": "81"}, {"text": "216"}], "correct_index": 1}'),
('pattern_recognition', 'matrices', '{6-8}', 0.5, 1.3, 0.20, '{"stem": "In this 3x3 grid, shapes rotate 90° across columns and change color across rows. What goes in the empty cell?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 2, "media": ["matrix_68_1.svg"]}'),
('pattern_recognition', 'spatial', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "Which 3D shape results from rotating this 2D cross-section 360° around the axis?", "type": "rotation_3d", "options": [{"text": "Sphere"}, {"text": "Cylinder"}, {"text": "Cone"}, {"text": "Torus"}], "correct_index": 2, "media": ["rotate3d_1.svg"]}'),
('pattern_recognition', 'matrices', '{6-8}', 1.0, 1.5, 0.20, '{"stem": "Two rules govern this grid: size increases left-to-right, shading alternates top-to-bottom. What completes it?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 0, "media": ["matrix_68_2.svg"]}'),
('pattern_recognition', 'sequences', '{6-8}', 1.5, 1.6, 0.15, '{"stem": "What comes next? 1, 3, 7, 15, 31, ___", "type": "number_pattern", "options": [{"text": "47"}, {"text": "55"}, {"text": "62"}, {"text": "63"}], "correct_index": 3}'),
('pattern_recognition', 'spatial', '{6-8}', 1.5, 1.7, 0.15, '{"stem": "This net folds into a cube. Which two faces are opposite each other?", "type": "nets", "options": [{"text": "A and C"}, {"text": "A and F"}, {"text": "B and E"}, {"text": "C and D"}], "correct_index": 1, "media": ["cube_net_1.svg"]}'),
('pattern_recognition', 'matrices', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "This 4x4 grid uses three simultaneous rules (shape, size, shading). What completes the bottom-right cell?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 1, "media": ["matrix_68_3.svg"]}'),
('pattern_recognition', 'spatial', '{6-8}', 2.0, 1.8, 0.15, '{"stem": "A paper is folded twice and a hole is punched. When unfolded, how many holes appear?", "type": "paper_fold", "options": [{"text": "2"}, {"text": "3"}, {"text": "4"}, {"text": "8"}], "correct_index": 2, "media": ["fold_68_1.svg"]}'),
('pattern_recognition', 'sequences', '{6-8}', 2.5, 2.0, 0.15, '{"stem": "What comes next? 1, 11, 21, 1211, 111221, ___", "type": "number_pattern", "options": [{"text": "312211"}, {"text": "122211"}, {"text": "1112221"}, {"text": "221121"}], "correct_index": 0}'),
('pattern_recognition', 'matrices', '{6-8}', 2.5, 1.9, 0.15, '{"stem": "This grid applies XOR logic to shapes: combining two shapes produces a third. What completes the pattern?", "type": "matrix", "options": [{"text": "Option A"}, {"text": "Option B"}, {"text": "Option C"}, {"text": "Option D"}], "correct_index": 3, "media": ["matrix_68_4.svg"]}'),
('pattern_recognition', 'spatial', '{6-8}', 3.0, 2.0, 0.15, '{"stem": "A cube has different patterns on each face. After the shown sequence of rotations, which face is on top?", "type": "mental_rotation", "options": [{"text": "Stripes"}, {"text": "Dots"}, {"text": "Solid"}, {"text": "Checkerboard"}], "correct_index": 1, "media": ["cube_rotate_1.svg"]}');
