/**
 * qa/seed-approved.ts
 *
 * Takes approved items from qa/approved/ and:
 *   1. Converts them to SQL INSERT statements for the Supabase items table
 *   2. Updates the demo items.ts file for client-side demo mode
 *
 * Usage:
 *   npx tsx qa/seed-approved.ts
 *
 * Output:
 *   - qa/seed-items.sql          (SQL INSERT statements)
 *   - apps/web/src/app/demo/items.ts  (updated demo items)
 */

import * as fs from "fs";
import * as path from "path";

// ─── Config ─────────────────────────────────────────────────────

const QA_DIR = path.resolve(__dirname);
const REPO_DIR = path.resolve(QA_DIR, "..");
const APPROVED_DIR = path.join(QA_DIR, "approved");
const SQL_OUTPUT = path.join(QA_DIR, "seed-items.sql");
const DEMO_ITEMS_PATH = path.join(
  REPO_DIR,
  "apps/web/src/app/demo/items.ts"
);

// ─── Load approved items ────────────────────────────────────────

interface ApprovedItem {
  id: string;
  domain: string;
  age_bands: string[];
  difficulty: number;
  discrimination: number;
  guessing: number;
  content: {
    stem: string;
    type: string;
    options: { text: string; image?: string; audio?: string }[];
    correct_index: number;
    explanation: string;
    media?: string[];
    audio_stem?: string;
  };
  metadata: {
    cognitive_skill: string;
    misconception_targeted: string;
    bloom_level: string;
    distractor_rationale?: {
      option_index: number;
      misconception_id: string;
      reasoning: string;
    }[];
    source_reference?: string;
  };
}

function loadApprovedItems(): ApprovedItem[] {
  if (!fs.existsSync(APPROVED_DIR)) {
    console.error(`ERROR: Approved directory not found: ${APPROVED_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(APPROVED_DIR).filter((f) => f.endsWith(".json"));

  if (files.length === 0) {
    console.error("ERROR: No approved items found in qa/approved/");
    console.error("Run the QA pipeline first: bash qa/run-micro-loops.sh");
    process.exit(1);
  }

  const items: ApprovedItem[] = [];

  for (const file of files) {
    try {
      const data = JSON.parse(
        fs.readFileSync(path.join(APPROVED_DIR, file), "utf-8")
      );
      if (Array.isArray(data)) {
        items.push(...data);
      } else if (data && typeof data === "object") {
        items.push(data as ApprovedItem);
      }
    } catch (error) {
      console.warn(`Warning: Could not parse ${file}:`, error);
    }
  }

  return items;
}

// ─── Generate SQL INSERT statements ─────────────────────────────

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''");
}

function generateSQL(items: ApprovedItem[]): string {
  const lines: string[] = [];

  lines.push("-- GT Challenge: Approved Item Bank Seed");
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push(`-- Items: ${items.length}`);
  lines.push("");
  lines.push("BEGIN;");
  lines.push("");

  for (const item of items) {
    // Build content_json (what the DB stores)
    const contentJson = {
      stem: item.content.stem,
      type: item.content.type,
      options: item.content.options,
      correct_index: item.content.correct_index,
      explanation: item.content.explanation,
      ...(item.content.media ? { media: item.content.media } : {}),
      ...(item.content.audio_stem ? { audio_stem: item.content.audio_stem } : {}),
    };

    // Map age_bands to PostgreSQL array literal
    const ageBandsLiteral = `ARRAY[${item.age_bands
      .map((b) => `'${b}'::age_band_type`)
      .join(", ")}]`;

    // Build subdomain from content type or metadata cognitive_skill
    const subdomain = item.metadata.cognitive_skill || item.content.type || "";

    lines.push(`INSERT INTO items (id, domain, subdomain, age_bands, difficulty, discrimination, guessing, content_json, teach_item, status)`);
    lines.push(`VALUES (`);
    lines.push(`  gen_random_uuid(),`);
    lines.push(`  '${escapeSQL(item.domain)}'::domain_type,`);
    lines.push(`  '${escapeSQL(subdomain)}',`);
    lines.push(`  ${ageBandsLiteral},`);
    lines.push(`  ${item.difficulty.toFixed(2)},`);
    lines.push(`  ${item.discrimination.toFixed(2)},`);
    lines.push(`  ${item.guessing.toFixed(2)},`);
    lines.push(`  '${escapeSQL(JSON.stringify(contentJson))}'::jsonb,`);
    lines.push(`  false,`);
    lines.push(`  'active'::item_status`);
    lines.push(`);`);
    lines.push("");
  }

  lines.push("COMMIT;");
  lines.push("");

  return lines.join("\n");
}

// ─── Generate demo items.ts ─────────────────────────────────────

function generateDemoItemsTS(items: ApprovedItem[]): string {
  const lines: string[] = [];

  lines.push("// Seed items for demo mode — no database needed");
  lines.push("// AUTO-GENERATED by qa/seed-approved.ts — do not edit manually");
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push("");
  lines.push("export interface DemoItem {");
  lines.push("  id: string;");
  lines.push("  domain: string;");
  lines.push("  ageBand: string;");
  lines.push("  difficulty: number;");
  lines.push("  discrimination: number;");
  lines.push("  guessing: number;");
  lines.push("  content: {");
  lines.push("    stem: string;");
  lines.push("    type: string;");
  lines.push("    options: { text: string }[];");
  lines.push("    correct_index: number;");
  lines.push("  };");
  lines.push("}");
  lines.push("");

  // Group items by age band
  const byBand: Record<string, ApprovedItem[]> = {
    "K-2": [],
    "3-5": [],
    "6-8": [],
  };

  for (const item of items) {
    const primaryBand = item.age_bands[0] || "3-5";
    if (byBand[primaryBand]) {
      byBand[primaryBand].push(item);
    }
  }

  // Generate each age band array
  const bandVarNames: Record<string, string> = {
    "K-2": "K2_ITEMS",
    "3-5": "ITEMS_3_5",
    "6-8": "ITEMS_6_8",
  };

  for (const [band, varName] of Object.entries(bandVarNames)) {
    const bandItems = byBand[band] || [];

    lines.push(`// ─── ${band} Items ─────────────────────────────────────────────────`);
    lines.push("");
    lines.push(`const ${varName}: DemoItem[] = [`);

    // Group by domain for readability
    const byDomain: Record<string, ApprovedItem[]> = {};
    for (const item of bandItems) {
      if (!byDomain[item.domain]) byDomain[item.domain] = [];
      byDomain[item.domain].push(item);
    }

    for (const [domain, domainItems] of Object.entries(byDomain)) {
      lines.push(`  // ${domain.charAt(0).toUpperCase() + domain.slice(1)}`);
      for (const item of domainItems) {
        const demoItem = {
          id: item.id,
          domain: item.domain === "pattern_recognition" ? "pattern" : item.domain,
          ageBand: band,
          difficulty: item.difficulty,
          discrimination: item.discrimination,
          guessing: item.guessing,
          content: {
            stem: item.content.stem,
            type: item.content.type,
            options: item.content.options.map((o) => ({ text: o.text })),
            correct_index: item.content.correct_index,
          },
        };
        lines.push(`  ${JSON.stringify(demoItem)},`);
      }
    }

    lines.push("];");
    lines.push("");
  }

  // Export
  lines.push("// ─── Export all items ──────────────────────────────────────────");
  lines.push("");
  lines.push('export const ALL_ITEMS: Record<string, DemoItem[]> = {');
  lines.push('  "K-2": K2_ITEMS,');
  lines.push('  "3-5": ITEMS_3_5,');
  lines.push('  "6-8": ITEMS_6_8,');
  lines.push("};");
  lines.push("");
  lines.push("/** @deprecated Use ALL_ITEMS instead */");
  lines.push("export const DEMO_ITEMS: DemoItem[] = ITEMS_3_5;");
  lines.push("");

  return lines.join("\n");
}

// ─── Main ───────────────────────────────────────────────────────

function main() {
  console.log("Loading approved items...");
  const items = loadApprovedItems();
  console.log(`Found ${items.length} approved items.`);

  // Group by domain/band for summary
  const summary: Record<string, number> = {};
  for (const item of items) {
    const key = `${item.domain}/${item.age_bands[0]}`;
    summary[key] = (summary[key] || 0) + 1;
  }

  console.log("\nItem distribution:");
  for (const [key, count] of Object.entries(summary).sort()) {
    console.log(`  ${key}: ${count}`);
  }

  // Generate SQL
  console.log(`\nGenerating SQL...`);
  const sql = generateSQL(items);
  fs.writeFileSync(SQL_OUTPUT, sql);
  console.log(`SQL written to: ${SQL_OUTPUT}`);

  // Generate demo items.ts
  console.log(`\nGenerating demo items.ts...`);
  const demoTS = generateDemoItemsTS(items);
  fs.writeFileSync(DEMO_ITEMS_PATH, demoTS);
  console.log(`Demo items written to: ${DEMO_ITEMS_PATH}`);

  // Final summary
  console.log(`\n--- Seed Summary ---`);
  console.log(`Total items:    ${items.length}`);
  console.log(`SQL file:       ${SQL_OUTPUT}`);
  console.log(`Demo items:     ${DEMO_ITEMS_PATH}`);
  console.log(`\nTo apply SQL to Supabase:`);
  console.log(`  supabase db push --db-url <your-db-url> < ${SQL_OUTPUT}`);
  console.log(`  # or copy/paste into the Supabase SQL editor`);
}

main();
